### PR TITLE
Add support for `show slave status` 

### PR DESCRIPTION
**Pull request by fulghum**
This syntax is deprecated and will be removed in future MySQL versions (`SHOW REPLICA STATUS` should be preferred instead). However, some tools (e.g. Dolphie, MyDumper) still rely on this deprecated syntax, so we're adding support for it to keep compatibility with those tools.

### CODE REVIEW

**Review by jycor — APPROVED** [review]
LGTM

**Comment by davidducos** [comment]
Hi @fulghum, MyDumper supports both (SLAVE and REPLICA) and depending on the version determine which is the best to use, which in MySQL is since version 8.0.22. 
I check the version that Dolt is reporting and it says 8.0.11, that is why mydumper uses SLAVE, instead of REPLICA, if you start using a version number above 22, it will automatically change to REPLICA. BTW, I already working on this PR https://github.com/mydumper/mydumper/pull/1684 in case that you know specific cases that you want to implement for Dolt. Please, let me know if  you consider this useful, if not, it will consider as a Unknown version and it will apply the same rules than MySQL and Percona. 
Cheers

**Comment by fulghum** [comment]
Hi @davidducos, thanks for chiming in! Awesome to see that you've already got a PR in progress with some changes to better support Dolt! 🙌  Thank you! @jycor is working on some Dolt changes on on our side, too, so we'll get him to try out sending a different MySQL version number and to take a look at the PR you linked to. Thanks for the help!

**Comment by davidducos** [comment]
Ok, the PR on mydumper side is on hold now, until we get the version number on Dolt, as we could use just 8.0.11 but I want your users get a better experience setting the right number. Please let me know so I can merge that. 
Cheers!

**Pull request merged**
