### PR TITLE
add serial supoort

### PR DESCRIPTION
**Pull request by sillydong**
add serial support https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html#:~:text=SERIAL

### CODE REVIEW

**Comment by sillydong** [comment]
@zachmu @andrew-wm-arthur could you help review this PR. Thanks

**Review by zachmu — APPROVED** [review]
Looks great, thanks for the contribution!

**Comment by zachmu** [comment]
Looks great but you'll need to regen sql.go since I merged your other PR

**Comment by sillydong** [comment]
@zachmu Hi, sorry for the delay. I rebased and regenerated the sql.go. Please feel free to process to next step. Thanks.

**Review by zachmu — APPROVED** [review]

**Pull request merged**
