### PR TITLE
supports `FROM s.account`, in which `account` is non-reserved keyword

### PR DESCRIPTION
**Pull request by boyxuper**

### CODE REVIEW

**Comment by boyxuper** [comment]
Hi, I just re-generated sql.go with goyacc v0.1.9, please rerun checks.

**Comment by zachmu** [comment]
Looks fine to me, @jycor can you validate?

**Review by zachmu — APPROVED** [review]
LGTM

**Review by jycor — APPROVED** [review]
LGTM!

**Pull request merged**
