### PR TITLE
Small parser fixes for stored procedures

### PR DESCRIPTION
**Pull request by Hydrocharged**

### CODE REVIEW

**Review by zachmu — APPROVED** [review]
LGTM

Parse tests for trying to include an unsupported statement?

**Comment by Hydrocharged** [comment]
This does the opposite, `statement_list` is more restrictive than `proc_allowed_statement_list`, so I opened it up. I should probably just allow the parser to parse more than what's actually applicable and the engine can filter as needed. Triggers, stored procedures, stored functions, prepared statements...they all have subtle differences (or not so subtle) differences in what's allowed in a block. But having 5 different `xyz_statement_list`  rules with their corresponding `BEGIN/END`, etc. rules just complicates the grammar too much I think.

Thoughts on this?

**Comment by zachmu** [comment]
For now I don't think it matters that much, but in the end we want to have the same behavior as MySQL, including in the parser. If it's the case that MySQL refuses to parse something, we should generally do the same. But I think it's fine to kick that can down the road a bit on this.

**Comment by Hydrocharged** [comment]
Okay. In that case I'll just unify them for now and we can split them later once our parsing story is more mature.

**Pull request merged**
